ARG SWITCHER_TAG="master"

FROM "registry.gitlab.com/sat-metalab/switcher":deps-ubuntu1804 AS build
LABEL MAINTAINER="Metalab <metalab-dev@sat.qc.ca>"

ARG BUILD_DIR="/opt/switcher"

ENV NVIDIA_DRIVER_CAPABILITIES="all"

# Set switcher paths
WORKDIR ${BUILD_DIR}
COPY . ${BUILD_DIR}

# Build and install switcher
RUN mkdir -p build \
    && cd build \
    && CC="gcc-8" CXX="g++-8" cmake -DENABLE_GPL=ON -DCMAKE_BUILD_TYPE="Release" .. \
    && make -j"$(nproc)" \
    && make install \
    && ldconfig

# Remove build folder and clean apt cache
RUN DEBIAN_FRONTEND=noninteractive apt remove -y -qq \
       $(cat ${BUILD_DIR}/deps/apt-build-ubuntu-18.04) \
       $(cat ${BUILD_DIR}/deps/apt-build-nvidia-deps-ubuntu-18.04) \
    && SUDO_FORCE_REMOVE=yes apt autoremove -y \
    && apt autoclean \
    && rm -rf /var/lib/{apt,dpkg,cache,log}/ \
    && cd / && rm -rf ${BUILD_DIR}
